# Generated by Django 2.0.5 on 2018-06-01 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capturado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2018, 6, 1, 16, 23, 8, 856288), verbose_name='Fecha de Acceso')),
                ('ip', models.TextField(null=True)),
                ('ip_extra', models.TextField(null=True)),
                ('is_ruteable', models.BooleanField(default=True)),
                ('meta', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50, null=True)),
                ('objetivo', models.TextField(max_length=50, null=True)),
                ('link_destino', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='capturado',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunter.Link'),
        ),
    ]
