# Generated by Django 2.0.5 on 2018-06-01 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturado',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 1, 16, 24, 45, 162408), verbose_name='Fecha de Acceso'),
        ),
    ]
