# Generated by Django 2.0.4 on 2018-04-17 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0008_merge_20180417_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturado',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 18, 14, 28, 80209), verbose_name='Fecha de Acceso'),
        ),
    ]
