# Generated by Django 2.0.3 on 2018-05-03 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0009_auto_20180417_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturado',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 10, 39, 27, 143175), verbose_name='Fecha de Acceso'),
        ),
    ]
