# Generated by Django 2.0.3 on 2018-05-07 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0010_auto_20180503_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturado',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 9, 41, 13, 442389), verbose_name='Fecha de Acceso'),
        ),
    ]
