# Generated by Django 2.0.2 on 2018-05-07 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0011_auto_20180507_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturado',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 10, 20, 0, 289563), verbose_name='Fecha de Acceso'),
        ),
    ]
