# Generated by Django 2.0.5 on 2018-05-15 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 13, 18, 56, 946494), verbose_name='Fecha de Publicacion'),
        ),
    ]
