# Generated by Django 2.0.3 on 2018-04-17 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180417_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 17, 18, 31, 135771), verbose_name='Fecha de Publicacion'),
        ),
    ]
