# Generated by Django 2.0.4 on 2018-04-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180417_1808'),
        ('core', '0008_auto_20180417_1756'),
    ]

    operations = [
    ]
