# Generated by Django 2.0.4 on 2018-04-17 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20180417_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 18, 14, 28, 71641), verbose_name='Fecha de Publicacion'),
        ),
    ]
