# Generated by Django 2.0.3 on 2018-05-07 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180503_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 9, 41, 13, 438618), verbose_name='Fecha de Publicacion'),
        ),
    ]
