# Generated by Django 2.0.2 on 2018-05-07 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180507_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 10, 20, 0, 286412), verbose_name='Fecha de Publicacion'),
        ),
    ]
