# Generated by Django 2.0.5 on 2018-06-01 19:37

import datetime
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descripcion', tinymce.models.HTMLField()),
                ('captura', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='archivos/'), upload_to='')),
                ('archivo', models.FileField(upload_to='')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 6, 1, 16, 37, 55, 56561), verbose_name='Fecha de Publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Archivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
