# Generated by Django 2.0.3 on 2018-04-03 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('nombre', models.TextField(max_length=50, null=True)),
                ('apellido', models.TextField(max_length=50, null=True)),
                ('localidad', models.CharField(blank=True, max_length=30)),
                ('telefono', models.TextField(max_length=20, null=True)),
                ('empresa', models.TextField(max_length=100, null=True)),
                ('producto', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
