# Generated by Django 2.0.3 on 2018-04-17 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capturado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2018, 4, 17, 14, 21, 1, 607027), verbose_name='Fecha de Acceso')),
                ('request', models.TextField(null=True)),
                ('ip', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50, null=True)),
                ('objetivo', models.TextField(max_length=50, null=True)),
                ('link_destino', models.URLField()),
            ],
        ),
    ]
