# Generated by Django 2.0.3 on 2018-04-17 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturado',
            name='is_ruteable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='capturado',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 14, 32, 31, 531341), verbose_name='Fecha de Acceso'),
        ),
    ]
