# Generated by Django 2.0.3 on 2018-04-17 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0002_auto_20180417_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturado',
            name='ip_extra',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='capturado',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 16, 59, 27, 535243), verbose_name='Fecha de Acceso'),
        ),
    ]
