# Generated by Django 2.0.3 on 2018-04-17 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0003_auto_20180417_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capturado',
            old_name='request',
            new_name='header',
        ),
        migrations.AlterField(
            model_name='capturado',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 17, 18, 31, 142530), verbose_name='Fecha de Acceso'),
        ),
    ]
