# Generated by Django 2.0.4 on 2018-04-17 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0006_auto_20180417_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturado',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 17, 56, 34, 423832), verbose_name='Fecha de Acceso'),
        ),
    ]
