# Generated by Django 2.0.3 on 2018-04-17 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 14, 21, 1, 590176), verbose_name='Fecha de Publicacion'),
        ),
    ]
