# Generated by Django 2.0.3 on 2018-04-17 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180417_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 16, 59, 27, 528263), verbose_name='Fecha de Publicacion'),
        ),
    ]
