# Generated by Django 2.0.3 on 2018-04-17 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180417_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 18, 8, 9, 212593), verbose_name='Fecha de Publicacion'),
        ),
    ]
